[package]
name = "arkin-backoffice"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arkin-common = { path = "../arkin-common" }

serde = { workspace = true }
rust_decimal = { workspace = true }
