[package]
name = "arkin-engine"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arkin-core = { path = "../arkin-core" }
arkin-execution = { path = "../arkin-execution" }
arkin-persistance = { path = "../arkin-persistance" }
arkin-insights = { path = "../arkin-insights" }
arkin-strategies = { path = "../arkin-strategies" }
arkin-allocation = { path = "../arkin-allocation" }
arkin-portfolio = { path = "../arkin-portfolio" }
arkin-market = { path = "../arkin-market" }

tokio = { workspace = true }
tracing = { workspace = true }
time = { workspace = true }
