[package]
name = "test-integration"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]



[dev-dependencies]
arkin-core = { path = "../arkin-core" }
arkin-engine = { path = "../arkin-engine" }
arkin-execution = { path = "../arkin-execution" }
arkin-persistance = { path = "../arkin-persistance" }
arkin-insights = { path = "../arkin-insights" }
arkin-strategies = { path = "../arkin-strategies" }
arkin-allocation = { path = "../arkin-allocation" }
arkin-portfolio = { path = "../arkin-portfolio" }
arkin-market = { path = "../arkin-market" }
test-utils = { path = "../test-utils" }

ctor = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
time = { workspace = true }
rstest = { workspace = true }