[package]
name = "arkin-strategies"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arkin-common = { path = "../arkin-common" }

rayon = { workspace = true }
time = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }