version: '3'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: arkin-tsdb
    environment:
      POSTGRES_DB: arkin_test
      POSTGRES_USER: arkin_admin
      POSTGRES_PASSWORD: test1234
    ports:
      - "5432:5432"
    volumes:
      - ./data/timescaledb/data:/var/lib/postgresql/data
      - ./data/timescaledb/logs:/var/logs
    networks:
      - grafana_network

  grafana:
    image: grafana/grafana-oss
    container_name: arkin-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - grafana_network

networks:
  grafana_network:
    driver: bridge