[package]
name = "arkin-core"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
config = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
time = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
derive_builder = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }