name: Arkin

ingestors:
  - binance:
      ws_url: wss://fstream.binance.com/ws
      ws_channels:
        - btcusdt@aggTrade
        - btcusdt@bookTicker
      connections_per_manager: 1
      duplicate_lookback: 100

state:
  market_state:
    enabled: true
  portfolio:
    enabled: true
  order_manager:
    enabled: true
  time_component:
    tick_frequency: 1 # In seconds

pipelines:
  - name: TA
    frequency: 1 # In seconds
    features:
      - vwap:
          id: vwap_1_min
          window: 60 # In seconds
      - vwap:
          id: vwap_1_h
          window: 3600 # In seconds
      - volume:
          id: volume_1_min
          window: 60 # In seconds
      - volume:
          id: volume_1_h
          window: 3600 # In seconds
      - sma:
          id: sma_10_min
          source: vwap_1_min
          window: 600 # In seconds
      - ema:
          id: ema_10_min
          source: vwap_1_min
          window: 600 # In seconds
      - spread:
          id: spread_sma_ema_10_minute
          front_component: ema_10_min
          back_component: sma_10_min

strategies:
  - crossover:
      id: crossover_vwap_half_pct
      fast: vwap_10_60
      slow: vwap_10_300
      min_spread: 0.005
  - crossover:
      id: crossover_vwap_one_pct
      fast: vwap_10_60
      slow: vwap_10_300
      min_spread: 0.01

allocation:
  limited:
    max_allocation: 0.1

execution:
  # - binance:
  #     max_orders_per_minute: 5
  #     max_order_size_notional: 1000.
  #     min_order_size_notional: 100.
  - backtest:
      max_orders_per_minute: 5
      max_order_size_notional: 1000.
      min_order_size_notional: 100.

tardis:
  base_url: https://api.tardis.dev/v1/data-feeds
  max_concurrent_requests: 1
  subscriptions:
    - exchange: binance_swap
      start: 2023-10-01 00:00:00
      channels:
        - agg_trade
        - book
      symbols:
        - BTCUSDT
        - ETHUSDT
        - SOLUSDT

clickhouse:
  url: http://127.0.0.1:18123
  user: arkin_admin
  database: arkin
