server:
  name: arkin

clock:
  tick_frequency: 1 # In seconds

state:
  window: 600 # In seconds

db:
  host: 127.0.0.1
  port: 5432
  user: arkin_admin
  database: arkin
  min_connections: 10
  max_connections: 200
  idle_timeout: 300

ingestors:
  - binance:
      ws_url: wss://fstream.binance.com/ws
      ws_channels:
        - btcusdt@aggTrade
        - btcusdt@bookTicker
      connections_per_manager: 1
      duplicate_lookback: 100
  # - tardis:
  #     base_url: https://api.tardis.dev/v1/data-feeds
  #     max_concurrent_requests: 1
  #     subscriptions:
  #       - exchange: binance_swap
  #         start: 2024-06-01 00:00:00
  #         channels:
  #           - agg_trade
  #           - ticker
  #           - book
  #         symbols:
  #           - btcusdt

feature_pipeline:
  name: feature
  frequency: 1 # In seconds
  features:
    # Volume
    - volume:
        id: volume_1_min
        window: 60 # In seconds
    - sma:
        id: sma_5_volume
        source: volume_1_min
        period: 5
    - sma:
        id: sma_60_volume
        source: volume_1_min
        period: 60
    - spread:
        id: spread_sma_volume
        front_component: sma_5_volume
        back_component: sma_60_volume
    # VWAP
    - vwap:
        id: vwap_1_min
        window: 60 # In seconds
    - sma:
        id: sma_5_vwap
        source: vwap_1_min
        period: 5
    - sma:
        id: sma_60_vwap
        source: vwap_1_min
        period: 60
    - spread:
        id: spread_sma_vwap
        front_component: sma_5_vwap
        back_component: sma_60_vwap

analytics_pipeline:
  name: analytics
  frequency: 1 # In seconds
  features:
    - position

strategy_manager:
  strategies:
    - crossover:
        id: crossover
        price_spread_id: spread_sma_vwap
        volume_spread_id: spread_sma_volume

allocation_manager:
  allocations:
    - equal:
        capital: 10000.
        max_allocation: 0.9
        max_allocation_per_instrument: 0.1
        strategies:
          - crossover

execution:
  - binance:
      max_orders_per_minute: 5
      max_order_size_notional: 1000.
      min_order_size_notional: 100.

simulation:
  latency: 5 # In ms
  commission_maker: 0.00012
  commission_taker: 0.0003
  max_orders_per_minute: 5
  max_order_size_notional: 1000.
  min_order_size_notional: 100.
