server:
  name: arkin

clock:
  tick_frequency: 1 # In seconds

state:
  window: 600 # In seconds

db:
  host: 127.0.0.1
  port: 5432
  user: arkin_admin
  database: arkin
  min_connections: 10
  max_connections: 200
  idle_timeout: 300

ingestors:
  - binance:
      ws_url: wss://fstream.binance.com/ws
      ws_channels:
        - btcusdt@aggTrade
        - btcusdt@bookTicker
      connections_per_manager: 1
      duplicate_lookback: 100
  # - tardis:
  #     base_url: https://api.tardis.dev/v1/data-feeds
  #     max_concurrent_requests: 1
  #     subscriptions:
  #       - exchange: binance_swap
  #         start: 2024-06-01 00:00:00
  #         channels:
  #           - agg_trade
  #           - ticker
  #           - book
  #         symbols:
  #           - btcusdt

pipeline:
  name: TA
  frequency: 1 # In seconds
  features:
    - vwap:
        id: vwap_1_min
        window: 60 # In seconds
    - vwap:
        id: vwap_1_h
        window: 3600 # In seconds
    - volume:
        id: volume_1_min
        window: 60 # In seconds
    - volume:
        id: volume_1_h
        window: 3600 # In seconds
    - sma:
        id: sma_10_min
        source: vwap_1_min
        period: 10
    - sma:
        id: sma_60_min
        source: vwap_1_min
        period: 60
    - spread:
        id: spread_sma
        front_component: sma_10_min
        back_component: sma_60_min

strategies:
  - crossover:
      id: crossover_vwap_half_pct
      fast: vwap_10_60
      slow: vwap_10_300
      min_spread: 0.005
  - crossover:
      id: crossover_vwap_one_pct
      fast: vwap_10_60
      slow: vwap_10_300
      min_spread: 0.01

allocation:
  limited:
    max_allocation: 0.1

execution:
  # - binance:
  #     max_orders_per_minute: 5
  #     max_order_size_notional: 1000.
  #     min_order_size_notional: 100.
  - backtest:
      max_orders_per_minute: 5
      max_order_size_notional: 1000.
      min_order_size_notional: 100.
