database:
  host: 127.0.0.1
  port: 5432
  user: arkin_admin
  password: test1234
  database: arkin
  min_connections: 10
  max_connections: 200
  idle_timeout: 300

portfolio_manager:
  initial_capital: 100000
  leverage: 1

market_manager:
  lookback_min: 1440

insights_manager:
  pipeline:
    frequency: 1 # In seconds
    features:
      # Volume
      - sum:
          id: volume
          input:
            from: base
            feature: trade_quantity
            window: 5
          output: volume
      - sma:
          id: sma_5_volume
          input:
            from: volume
            feature: volume
            periods: 5
          output: sma_5_volume
      - sma:
          id: sma_60_volume
          input:
            from: volume
            feature: volume
            periods: 60
          output: sma_60_volume
      - spread:
          id: spread_sma_volume
          input_front:
            from: sma_5_volume
            feature: sma_5_volume
          input_back:
            from: sma_60_volume
            feature: sma_60_volume
          output: spread_sma_volume
          absolute: false
      # VWAP
      - vwap:
          id: vwap
          input_price:
            from: base
            feature: trade_price
            window: 5
          input_quantity:
            from: base
            feature: trade_quantity
            window: 5
          output: vwap
      - sma:
          id: sma_5_vwap
          input:
            from: vwap
            feature: vwap
            periods: 5
          output: sma_5_vwap
      - sma:
          id: sma_60_vwap
          input:
            from: vwap
            feature: vwap
            periods: 60
          output: sma_60_vwap
      - spread:
          id: spread_sma_vwap
          input_front:
            from: sma_5_vwap
            feature: sma_5_vwap
          input_back:
            from: sma_60_vwap
            feature: sma_60_vwap
          output: spread_sma_vwap
          absolute: false

strategy_manager:
  strategies:
    - crossover:
        id: crossover
        price_spread_id: spread_sma_vwap
        volume_spread_id: spread_sma_volume

allocation_manager:
  module:
    equal:
      max_allocation: 0.9
      max_allocation_per_underlier: 0.25

execution_manager:
  default_endpoint: simulation
  endpoints:
    - simulation:
        latency: 0.1
        commission_maker: 0.0001
        commission_taker: 0.0002
        max_orders_per_minute: 1000
        max_order_size_notional: 100000
        min_order_size_notional: 100
