[package]
name = "arkin-ingestors"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arkin-core = { path = "../arkin-core" }

anyhow = { workspace = true }
async-tungstenite = { workspace = true }
flume = { workspace = true }
time = { workspace = true }
futures-util = { workspace = true }
tokio-rustls = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bytes = { workspace = true }
backoff = { workspace = true }
reqwest = { workspace = true }
rust_decimal = { workspace = true }