// https://api.tardis.dev/v1/exchanges
// {
//     "id": "okex-futures",
//     "name": "OKX Futures",
//     "enabled": true,
//     "supportsDatasets": true,
//     "availableSince": "2019-03-30T00:00:00.000Z",
//     "availableChannels": [
//         "futures/trade",
//         "futures/depth",
//         "futures/depth_l2_tbt",
//         "futures/ticker",
//         "futures/mark_price",
//         "futures/liquidation",
//         "index/ticker",
//         "system/status",
//         "information/sentiment",
//         "information/long_short_ratio",
//         "information/margin",
//         "trades",
//         "trades-all",
//         "books-l2-tbt",
//         "bbo-tbt",
//         "books",
//         "tickers",
//         "open-interest",
//         "mark-price",
//         "price-limit",
//         "status",
//         "instruments",
//         "index-tickers",
//         "long-short-account-ratio",
//         "taker-volume",
//         "liquidations",
//         "estimated-price",
//         "public-block-trades",
//         "public-struc-block-trades",
//         "liquidation-orders"
//     ]
// },
