/*
 * Binance Derivatives Trading USDS Futures WebSocket Market Streams
 *
 * OpenAPI Specification for the Binance Derivatives Trading USDS Futures WebSocket Market Streams
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::derivatives_trading_usds_futures::websocket_streams::models;
use arkin_core::prelude::*;
use rust_decimal::Decimal;
use serde::{de::Error, Deserialize, Deserializer, Serialize};
use serde_json::Value;
use time::UtcDateTime;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndividualSymbolBookTickerStreamsResponse {
    #[serde(rename = "e")]
    pub event_type: String,
    #[serde(rename = "E", with = "custom_serde::timestamp")]
    pub event_time: UtcDateTime,
    #[serde(rename = "T", with = "custom_serde::timestamp")]
    pub transaction_time: UtcDateTime,
    #[serde(rename = "u")]
    pub update_id: u64,
    #[serde(rename = "s")]
    pub instrument: String,
    #[serde(rename = "b")]
    pub bid_price: Decimal,
    #[serde(rename = "B")]
    pub bid_quantity: Decimal,
    #[serde(rename = "a")]
    pub ask_price: Decimal,
    #[serde(rename = "A")]
    pub ask_quantity: Decimal,
}
