name: Aurelion

ingestors:
  - binance:
      ws_url: wss://fstream.binance.com/ws
      ws_channels:
        - btcusdt@aggTrade
        - btcusdt@bookTicker
      connections_per_manager: 1
      duplicate_lookback: 100

state:
  market_state:
    enabled: true
  portfolio:
    enabled: true
  order_manager:
    enabled: true

features:
  - vwap:
      window: 10
  # - sma:
  #     window: 50
  # - sma:
  #     window: 200
  # - ema:
  #     window: 50
  # - ema:
  #     window: 200

traders:
  wide_quoter:
    strategy:
      wide_quoter:
        spread_in_pct: 1.
    allocation:
      limited:
        max_allocation: 0.1

  spreader:
    strategy:
      spreader:
        front_leg: BTCUSDT
        back_leg: ETHUSDT
        min_spread: 0.1
    allocation:
      limited:
        max_allocation: 0.1

execution:
  # - binance:
  #     max_orders_per_minute: 5
  #     max_order_size_notional: 1000.
  #     min_order_size_notional: 100.
  - backtest:
      max_orders_per_minute: 5
      max_order_size_notional: 1000.
      min_order_size_notional: 100.

tardis:
  base_url: https://api.tardis.dev/v1/data-feeds
  max_concurrent_requests: 1
  subscriptions:
    - exchange: binance_swap
      start: 2023-10-01 00:00:00
      channels:
        - agg_trade
        - book
      symbols:
        - BTCUSDT
        - ETHUSDT
        - SOLUSDT

clickhouse:
  url: http://127.0.0.1:18123
  user: aurelion_admin
  database: aurelion
