name: Aurelion

ingestors:
  - binance:
      ws_url: wss://fstream.binance.com/ws
      ws_channels:
        - btcusdt@aggTrade
      connections_per_manager: 2
      duplicate_lookback: 1000

state:
  market_state:
    enabled: true
  portfolio:
    enabled: true
  order_manager:
    enabled: true

features:
  - vwap:
      window: 10
  # - sma:
  #     window: 50
  # - sma:
  #     window: 200
  # - ema:
  #     window: 50
  # - ema:
  #     window: 200

traders:
  wide_quoter:
    strategy:
      wide_quoter:
        spread_in_pct: 1.
    allocation:
      limited:
        max_allocation: 0.1

  spreader:
    strategy:
      spreader:
        front_leg: BTCUSDT
        back_leg: ETHUSDT
        min_spread: 0.1
    allocation:
      limited:
        max_allocation: 0.1

execution:
  - binance:
      max_orders_per_minute: 5
      max_order_size_notional: 1000.
      min_order_size_notional: 100.
