name: Aurelion

ingestors:
  binance:
    usdm_trades:
      enabled: true
      ws_url: wss://fstream.binance.com/ws
      ws_channels:
        - btcusdt@aggTrade
      connections_per_manager: 2
      duplicate_lookback: 1000

state:
  market_state:
    enabled: true
  portfolio:
    enabled: true
  order_manager:
    enabled: true
