database:
  host: 127.0.0.1
  port: 5432
  user: arkin_admin
  password: test1234
  database: arkin_test
  min_connections: 10
  max_connections: 200
  idle_timeout: 300

ingestor_service:
  ingestors:
    - binance:
        ws_url: wss://fstream.binance.com/ws
        ws_channels:
          - btcusdt@aggTrade
          - btcusdt@bookTicker
        connections_per_manager: 2
        duplicate_lookback: 1000
  # - tardis:
  #     base_url: https://api.tardis.dev/v1/data-feeds
  #     max_concurrent_requests: 1
  #     subscriptions:
  #       - exchange: binance_swap
  #         start: 2024-06-01 00:00:00
  #         channels:
  #           - agg_trade
  #           - ticker
  #           - book
  #         symbols:
  #           - btcusdt

portfolio_manager:
  initial_capital: 100000
  leverage: 1

market_manager:
  lookback_min: 1440

strategy_manager:
  strategies:
    - crossover:
        id: crossover
        price_spread_id: spread_sma_vwap
        volume_spread_id: spread_sma_volume

allocation_manager:
  module:
    simple:
      max_allocation: 0.9
      max_allocation_per_signal: 0.1

execution_manager:
  default_endpoint: simulation
  endpoints:
    - simulation:
        latency: 0.1
        commission_maker: 0.0001
        commission_taker: 0.0002
        max_orders_per_minute: 1000
        max_order_size_notional: 100000
        min_order_size_notional: 100
