# The following data is usually available
# - trade_price
# - trade_quantity
# - trade_side
# - bid_price
# - bid_quantity
# - ask_price
# - ask_quantity
# - mid_price
insights_service:
  pipeline:
    features:
      - ohlcv:
          input_price: trade_price
          input_quantity: trade_quantity
          output_open: open
          output_high: high
          output_low: low
          output_close: close
          output_volume: volume
          output_notional_volume: notional_volume
          window: 60
      - vwap:
          input_price: trade_price
          input_quantity: trade_quantity
          output: vwap
          window: 60
      - pct_change:
          input: close
          output: return
          periods: 2
      - trade_count:
          trade_side_input: trade_side
          buy_output: buy_count
          sell_output: sell_count
          total_output: total_count
          ratio_output: buy_sell_ratio
          window: 60
      - std_dev:
          input: return
          output: return_stddev
          periods: 60
      - hist_vol:
          input: return_stddev
          output: annualized_hist_vol
          trading_days_per_year: 365
          timeframe_in_secs: 60
      - sma:
          input: close
          output: sma_5
          periods: 5
      - sma:
          input: close
          output: sma_60
          periods: 60
      - ema:
          input: close
          output: ema_12
          periods: 12
          smoothing: 2
      - ema:
          input: close
          output: ema_26
          periods: 26
          smoothing: 2
      - macd:
          fast_input: ema_12
          slow_input: ema_26
          signal_output: macd_signal
          histogram_output: macd_histogram
          signal_periods: 9
          smoothing: 2
