# The following data is usually available
# - trade_price
# - trade_quantity
# - trade_side
# - bid_price
# - bid_quantity
# - ask_price
# - ask_quantity
# - mid_price
insights_service:
  pipeline:
    features:
      - ohlcv:
          input_price: trade_price
          input_quantity: trade_quantity
          output_open: open
          output_high: high
          output_low: low
          output_close: close
          output_typical_price: typical_price
          output_vwap: vwap_price
          output_volume: volume
          output_buy_volume: buy_volume
          output_sell_volume: sell_volume
          output_notional_volume: notional_volume
          output_buy_notional_volume: buy_notional_volume
          output_sell_notional_volume: sell_notional_volume
          output_trade_count: trade_count
          output_buy_trade_count: buy_trade_count
          output_sell_trade_count: sell_trade_count
          window: 60
      - pct_change:
          input: close
          output: return
          periods: 1
      - std_dev:
          input: return
          output: return_stddev
          periods: 60
      - std_dev:
          input: close
          output: stddev_20
          periods: 20
      - hist_vol:
          input: return_stddev
          output: annualized_hist_vol
          trading_days_per_year: 365
          timeframe_in_secs: 60
      - sma:
          input: close
          output: sma_20
          periods: 20
      - sma:
          input: close
          output: sma_60
          periods: 60
      - ema:
          input: close
          output: ema_12
          periods: 12
          smoothing: 2
      - ema:
          input: close
          output: ema_26
          periods: 26
          smoothing: 2
      - macd:
          input_fast: ema_12
          input_slow: ema_26
          output_signal: macd_signal
          output_histogram: macd_histogram
          signal_periods: 9
          smoothing: 2
      - bb:
          input_price: close
          input_sma: sma_20
          input_stddev: stddev_20
          output_upper: bb_upper
          output_lower: bb_lower
          output_oscillator: bb_oscillator
          output_width: bb_width
          sigma: 2
      - rsi:
          input_return: return
          output: rsi
          periods: 14
