# The following data is usually available
# - trade_price
# - trade_quantity
# - trade_side
# - bid_price
# - bid_quantity
# - ask_price
# - ask_quantity
# - mid_price
insights_service:
  pipeline:
    features:
      - count:
          inputs: [trade_side]
          outputs: [trade_count_m]
          window: 60
      - count:
          inputs: [bid_price, ask_price]
          outputs: [ob_spread_avg_m]
          #   type: avg
          #   absolute: false
          window: 60
      - count:
          inputs: [trade_count_m, ob_spread_avg_m]
          outputs: [trade_volume]
          window: 60
      - count:
          inputs: [trade_volume]
          outputs: [trade_count_h, trade_volume_h]
          window: 3600
      - count:
          inputs: [trade_count_h, trade_volume_h]
          outputs: [comp_1, comp_2, comp_3]
          window: 3600
      - count:
          inputs: [comp_1, comp_2]
          outputs: [forecast]
          window: 3600

      # - pct_change:
      #     id: returns
      #     input:
      #       from: base
      #       feature: trade_price
      #       window: 60
      #     output: returns
      # - cum_sum:
      #     id: cumulative_returns
      #     input:
      #       from: returns
      #       feature: returns
      #       window: 3600
      #     output: cumulative_returns
      # - std_dev:
      #     id: hist_vol
      #     input:
      #       from: returns
      #       feature: returns
      #       window: 3600
      #     output: hist_vol
      # # Volume
      # - sum:
      #     id: volume
      #     input:
      #       from: base
      #       feature: trade_quantity
      #       window: 60
      #     output: volume
      # - sma:
      #     id: sma_5_volume
      #     input:
      #       from: volume
      #       feature: volume
      #       periods: 5
      #     output: sma_5_volume
      # - sma:
      #     id: sma_5_volume
      #     input: volume
      #     periods: 5
      # - spread:
      #     input_front: sma_5_volume
      #     input_back: sma_60_volume
      #     absolute: false
      #     output: spread_sma_volume
      # - sma:
      #     id: sma_60_volume
      #     input:
      #       from: volume
      #       feature: volume
      #       periods: 60
      #     output: sma_60_volume
      # - spread:
      #     id: spread_sma_volume
      #     input_front:
      #       from: sma_5_volume
      #       feature: sma_5_volume
      #     input_back:
      #       from: sma_60_volume
      #       feature: sma_60_volume
      #     output: spread_sma_volume
      #     absolute: false
      # # VWAP
      # - vwap:
      #     id: vwap
      #     input_price:
      #       from: base
      #       feature: trade_price
      #       window: 60
      #     input_quantity:
      #       from: base
      #       feature: trade_quantity
      #       window: 60
      #     output: vwap
      # - sma:
      #     id: sma_5_vwap
      #     input:
      #       from: vwap
      #       feature: vwap
      #       periods: 5
      #     output: sma_5_vwap
      # - sma:
      #     id: sma_60_vwap
      #     input:
      #       from: vwap
      #       feature: vwap
      #       periods: 60
      #     output: sma_60_vwap
      # - spread:
      #     id: spread_sma_vwap
      #     input_front:
      #       from: sma_5_vwap
      #       feature: sma_5_vwap
      #     input_back:
      #       from: sma_60_vwap
      #       feature: sma_60_vwap
      #     output: spread_sma_vwap
      #     absolute: false
