// https://api.tardis.dev/v1/exchanges
// {
//     "id": "okex",
//     "name": "OKX Spot",
//     "enabled": true,
//     "supportsDatasets": true,
//     "availableSince": "2019-03-30T00:00:00.000Z",
//     "availableChannels": [
//         "spot/trade",
//         "spot/depth",
//         "spot/depth_l2_tbt",
//         "spot/ticker",
//         "system/status",
//         "margin/interest_rate",
//         "trades",
//         "trades-all",
//         "books-l2-tbt",
//         "bbo-tbt",
//         "books",
//         "tickers",
//         "interest-rate-loan-quota",
//         "vip-interest-rate-loan-quota",
//         "status",
//         "instruments",
//         "taker-volume",
//         "liquidations",
//         "public-block-trades",
//         "public-struc-block-trades"
//     ]
// },
