[package]
name = "arkin"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ingestors"
path = "src/bin/ingestors.rs"

[[bin]]
name = "insights"
path = "src/bin/insights.rs"


[dependencies]
arkin-core = { path = "../arkin-core" }
arkin-persistance = { path = "../arkin-persistance" }
arkin-ingestors = { path = "../arkin-ingestors" }
arkin-insights = { path = "../arkin-insights" }
#arkin-engine = { path = "../arkin-engine" }
#arkin-execution = { path = "../arkin-execution" }
#arkin-strategies = { path = "../arkin-strategies" }
#arkin-allocation = { path = "../arkin-allocation" }
#arkin-portfolio = { path = "../arkin-portfolio" }
#arkin-market = { path = "../arkin-market" }

tokio = { workspace = true }
mimalloc = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
tokio-rustls = { workspace = true }
time = { workspace = true }
anyhow = { workspace = true }
