[package]
name = "arkin"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "features"
path = "src/bin/features.rs"

[[bin]]
name = "ingestors"
path = "src/bin/ingestors.rs"

#[[bin]]
#name = "utils"
#path = "src/bin/utils.rs"


[dependencies]
arkin-common = { path = "../arkin-common" }
arkin-engine = { path = "../arkin-engine" }
arkin-execution = { path = "../arkin-execution" }
arkin-persistance = { path = "../arkin-persistance" }
arkin-ingestors = { path = "../arkin-ingestors" }
arkin-insights = { path = "../arkin-insights" }
arkin-strategies = { path = "../arkin-strategies" }
arkin-allocation = { path = "../arkin-allocation" }
arkin-portfolio = { path = "../arkin-portfolio" }
arkin-market = { path = "../arkin-market" }

tokio = { workspace = true }
mimalloc = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
tokio-rustls = { workspace = true }
time = { workspace = true }
