[package]
name = "arkin"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "features"
path = "src/bin/features.rs"

#[[bin]]
#name = "utils"
#path = "src/bin/utils.rs"

[dependencies]
arkin-common = { path = "../arkin-common" }

tokio = { workspace = true }
mimalloc = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
tokio-rustls = { workspace = true }
rstest.workspace = true
derive_builder = "0.20.0"
