[package]
name = "arkin-cli"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4.5", features = ["derive"] }
time = { workspace = true }
